---
- hosts: all
  # gather_facts: no
  roles:
    - role: common
      vars:
        - ansible_become: yes

- hosts: master
  gather_facts: no
  roles:
    - role: master

- hosts: worker
  gather_facts: no
  roles:
    - role: worker
