---
- name: Install kubeseal
  shell: |
    mkdir -p /tmp/kubedir
    curl -sSL https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/kubeseal-0.17.5-linux-arm64.tar.gz -o /tmp/kubedir/kubeseal.tar.gz
    tar xzvf /tmp/kubedir/kubeseal.tar.gz -C /tmp/kubedir
    sudo install -m 755 /tmp/kubedir/kubeseal /usr/local/bin/kubeseal
    rm -fr /tmp/kubedir

# https://github.com/bitnami-labs/sealed-secrets#how-can-i-do-a-backup-of-my-sealedsecrets
- name: Copy sealed-secrets master key
  copy:
    src: "{{ playbook_dir }}/kubeseal_master.key"
    dest: /tmp

- name: Install sealed-secrets custom resource
  shell: |
    kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml
    kubectl apply -f /tmp/kubeseal_master.key
    kubectl delete pod -n kube-system -l name=sealed-secrets-controller
    rm /tmp/kubeseal_master.key
